site_name: "> <"
site_url: https://docs.gt-lt.ml/
theme:
  language: 'zh-TW'
  name: material
  palette:
    scheme: default
    primary: black
    accent: light blue
    language: zh-TW
    font:
      text: Noto Sans Traditional Chinese
  features:
    - navigation.sections

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/F8GfF37GWh
      name: discord 支援伺服器
  search:
    language: 'zh_TW'
  custom_dir: overrides
  consent:
    title: Cookie
    description: >- 
      我們使用 cookie 來識別您的重複訪問和偏好，以衡量我們文檔的有效性以及用戶是否找到他們正在尋找的東西。徵得您的同意，您正在幫助我們使我們的文檔更好。
copyright: Copyright &copy; 2021 - 2022 AD
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
